from .Custom_ComfyUI_YoloWorld_EfficientSAM import YOLO_WORLD_EfficientSAM
from .Custom_ComfyUI_YoloWorld_EfficientSAM import YOLO_WORLD_SEGS
from .Custom_comfyui_llm_assistant import AssistantNodes
from .CROP_OBJECT import crop

NODE_CLASS_MAPPINGS = {**YOLO_WORLD_EfficientSAM.NODE_CLASS_MAPPINGS, **YOLO_WORLD_SEGS.NODE_CLASS_MAPPINGS, **AssistantNodes.NODE_CLASS_MAPPINGS, **crop.NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**YOLO_WORLD_EfficientSAM.NODE_DISPLAY_NAME_MAPPINGS, **YOLO_WORLD_SEGS.NODE_DISPLAY_NAME_MAPPINGS, **AssistantNodes.NODE_DISPLAY_NAME_MAPPINGS, **crop.NODE_DISPLAY_NAME_MAPPINGS}