[project]
name = "objectfusion_comfyui_nodes"
description = "This is a node to generate new image that combine 2 objects from different scene."
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["einops==0.8.0", "spandrel==0.3.4", "kornia==0.7.3", "nltk==3.9.1", "ollama==0.3.1", "openai==1.42.0", "opencv_python==4.8.0.76", "opencv_python_headless==4.10.0.84", "Pillow==10.4.0", "psutil==5.9.0", "PyYAML==6.0.2", "Requests==2.31.0", "safetensors==0.4.4", "scipy==1.14.1", "sentencepiece==0.2.0", "scikit-image==0.24.0", "supervision==0.22.0", "torch==2.4.0", "torchaudio==2.4.0", "torchsde==0.2.6", "torchvision==0.19.0", "tqdm==4.66.4", "transformers==4.44.0", "ultralytics==8.2.78", "websocket_client==1.8.0", "xformers==0.0.27.post2", "inference-gpu[yolo-world]==0.16.2", "bitsandbytes==0.43.3", "accelerate==0.33.0", "TensorImgUtils", "timm>=1.0.7"]

[project.urls]
Repository = "https://github.com/ducido/ObjectFusion_ComfyUI_nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "ducido"
DisplayName = "ObjectFusion_ComfyUI_nodes"
Icon = ""
